using Haley.Abstractions;
using Haley.Enums;
using Haley.Models;
using Haley.Utils;
using Microsoft.Extensions.Logging;
using Microsoft.VisualBasic;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Runtime.CompilerServices;
using System.Security.AccessControl;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.Xml.XPath;
using static Haley.Internal.IndexingConstant;
using static Haley.Internal.IndexingQueries;
using static System.Net.Mime.MediaTypeNames;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Haley.Utils {
    /// <summary>
    /// Partial class — vault hierarchy registration (client, module, workspace) and document registration.
    /// </summary>
    internal partial class MariaDBIndexing {
        /// <summary>
        /// Public entry point for document registration. Delegates to <c>RegisterDocumentsInternal</c>.
        /// </summary>
        /// <param name="holder">Receives the assigned DB ID and CUID after successful registration.</param>
        public async Task<(long id, Guid guid)> RegisterDocuments(IVaultReadRequest request, IVaultStorable holder) {
            return await RegisterDocumentsInternal(request, holder);
        }
        /// <summary>
        /// Upserts a client record in the core DB and updates its signing/encrypt/password keys.
        /// If the client already exists, only the display name, path, and keys are updated.
        /// Validates the DB schema via <c>EnsureValidation</c> before executing.
        /// </summary>
        public async Task<IFeedback> RegisterClient(IVaultClient info) {
            if (info == null) throw new ArgumentNullException("Input client directory info cannot be null");
            if (!info.TryValidate(out var msg)) throw new ArgumentException(msg);
            //We generate the hash_guid ourselves for the client.
            await EnsureValidation();

            //Do we even need to check if the client exists? Why dont' we directly upsert the values??? We need to check, because, if we try upsert, then each time , we end up with a new autogenerated id that is not consumed. So, we might end up with all ids' consumed in years. For safer side, we use upsert, also, we check if id exists and try to update separately.

            var exists = await _agw.Scalar(new AdapterArgs(_key) { Query = CLIENT.EXISTS }, (NAME, info.Name));
            var thandler = _agw.GetTransactionHandler(_key); //For both cases, update or upsert, we use inside a transaction.
            if (exists != null && long.TryParse(exists.ToString(), out var cliId)) {
                //Client exists. We just need to update.
                using (thandler.Begin()) {
                    //Register client
                    await _agw.NonQuery((new AdapterArgs(_key) { Query = CLIENT.UPDATE }).ForTransaction(thandler), (DNAME, info.DisplayName), (ID, cliId));
                    await _agw.NonQuery((new AdapterArgs(_key) { Query = CLIENT.UPSERTKEYS }).ForTransaction(thandler), (ID, cliId), (SIGNKEY, info.SigningKey), (ENCRYPTKEY, info.EncryptKey), (PASSWORD, info.PasswordHash));
                }
            } else {
                using (thandler.Begin()) {
                    //Register client
                    await _agw.NonQuery((new AdapterArgs(_key) { Query = CLIENT.INSERT }).ForTransaction(thandler), (NAME, info.Name), (DNAME, info.DisplayName), (GUID, info.Guid.ToString("N")));
                    exists = await _agw.Scalar((new AdapterArgs(_key) { Query = CLIENT.EXISTS }).ForTransaction(thandler), (NAME, info.Name));
                    if (exists != null && long.TryParse(exists.ToString(), out var clientId)) {
                        //Add Info
                        await _agw.NonQuery((new AdapterArgs(_key) { Query = CLIENT.UPSERTKEYS }).ForTransaction(thandler), (ID, clientId), (SIGNKEY, info.SigningKey), (ENCRYPTKEY, info.EncryptKey), (PASSWORD, info.PasswordHash));
                    }
                }
            }
            return await ValidateAndCache(CLIENT.EXISTS, "Client", info, null, (NAME, info.Name));
        }
        /// <summary>
        /// Upserts a module record in the core DB.
        /// If the module is new, also creates the per-module MariaDB schema via <c>CreateModuleDBInstance</c>
        /// (triggered through <c>ValidateAndCache</c>'s preProcess callback) and adds an adapter entry
        /// under the module's CUID.
        /// </summary>
        public async Task<IFeedback> RegisterModule(IVaultModule info) {
            if (info == null) throw new ArgumentNullException("Input Module directory info cannot be null");
            if (!info.TryValidate(out var msg)) throw new ArgumentNullException(msg);
            //We generate the hash_guid ourselves for the client.
            await EnsureValidation();

            //Check if client exists. If not throw exeception or don't register? //Send feedback.
            //var cexists = await _agw.Scalar(new AdapterArgs(_key) { Query = CLIENT.EXISTS }, (NAME, info.Client.Name));
            //if (cexists == null || !(cexists is int clientId)) throw new ArgumentException($@"Client {info.Client.Name} doesn't exist. Unable to index the module {info.DisplayName}.");
            //var mexists = await _agw.Scalar(new AdapterArgs(_key) { Query = MODULE.EXISTS }, (NAME, info.Name), (PARENT, clientId));
            var exists = await _agw.Scalar(new AdapterArgs(_key) { Query = MODULE.EXISTS_BY_CUID }, (CUID, info.Cuid.ToString("N")));
            if (exists != null && long.TryParse(exists.ToString(),out var mId)) {
                //Module exists. .just update it.
                await _agw.NonQuery(new AdapterArgs(_key) { Query = MODULE.UPDATE }, (DNAME, info.DisplayName), (ID, mId));
            } else {
                var cexists = await _agw.Scalar(new AdapterArgs(_key) { Query = CLIENT.EXISTS }, (NAME, info.Client.Name));
                if (cexists == null || !long.TryParse(cexists.ToString(), out var clientId)) throw new ArgumentException($@"Client {info.Client.Name} doesn't exist. Unable to index the module {info.DisplayName}.");
                await _agw.NonQuery(new AdapterArgs(_key) { Query = MODULE.INSERT }, (PARENT, clientId), (NAME, info.Name), (DNAME, info.DisplayName), (GUID, info.Guid.ToString("N")), (CUID, info.Cuid.ToString("N")));
            }
            return await ValidateAndCache(MODULE.EXISTS_BY_CUID, "Module", info, CreateModuleDBInstance, (CUID, info.Cuid.ToString("N")));
        }
        /// <summary>
        /// Upserts a workspace record in the core DB.
        /// On insert, validates the parent module exists first; on update, patches display name, path, and control/parse modes.
        /// </summary>
        public async Task<IFeedback> RegisterWorkspace(IVaultWorkSpace info) {
            if (info == null) throw new ArgumentNullException("Input Module directory info cannot be null");
            if (!info.TryValidate(out var msg)) throw new ArgumentNullException(msg);
            //We generate the hash_guid ourselves for the client.
            await EnsureValidation();

            var exists = await _agw.Scalar(new AdapterArgs(_key) { Query = WORKSPACE.EXISTS_BY_CUID }, (CUID, info.Cuid.ToString("N")));
            if (exists != null && long.TryParse(exists.ToString(), out var wsId)) {
                //Workspace exists — just update it.
                await _agw.NonQuery(new AdapterArgs(_key) { Query = WORKSPACE.UPDATE }, (DNAME, info.DisplayName), (STORAGE_REF, info.Base), (STORAGENAME_MODE, (int)info.StorageNameMode), (STORAGENAME_PARSE, (int)info.StorageNameParseMode), (ID, wsId));
            } else {
                var moduleCuid = StorageUtils.GenerateCuid(info.Client.Name, info.Module.Name);
                var mexists = await _agw.Scalar(new AdapterArgs(_key) { Query = MODULE.EXISTS_BY_CUID }, (CUID, moduleCuid));
                if (mexists == null || !long.TryParse(mexists.ToString(), out var modId)) throw new ArgumentException($@"Module {info.Module.Name} doesn't exist. Unable to index the module {info.DisplayName}.");
                await _agw.NonQuery(new AdapterArgs(_key) { Query = WORKSPACE.INSERT }, (PARENT, modId), (NAME, info.Name), (DNAME, info.DisplayName), (GUID, info.Guid.ToString("N")), (STORAGE_REF, info.Base), (CUID, info.Cuid.ToString("N")), (STORAGENAME_MODE, (int)info.StorageNameMode), (STORAGENAME_PARSE, (int)info.StorageNameParseMode));
            }
            return await ValidateAndCache(WORKSPACE.EXISTS_BY_CUID, "Workspace", info, null, (CUID, info.Cuid.ToString("N")));
        }
        /// <summary>
        /// Creates the core <c>dss_core</c> schema from the <c>dsscore.sql</c> template if it does not already exist.
        /// Called once at startup via <c>EnsureValidation</c>.
        /// </summary>
        public async Task Validate() {
            //var toReplace = new Dictionary<string, string> { ["lifecycle_state"] = }
               await _agw.CreateDatabase(new DbCreationArgs(_key) {
                ContentProcessor = (content, dbname) => {
                    //Custom processor to set the DB name in the SQL content.
                    return content.Replace(DB_CORE_SEARCH_TERM, dbname);
                },
                FallBackDBName = DB_CORE_FALLBACK_NAME,
                SQLPath = Path.Combine(AssemblyUtils.GetBaseDirectory(), DB_SQL_FILE_LOCATION, DB_CORE_SQL_FILE)
            });
        }
    }
}
