using Haley.Abstractions;
using Haley.Enums;
using System;
using System.Collections.Generic;
using System.Text;

namespace Haley.Models {
    /// <summary>
    /// Represents a workspace within the vault hierarchy (client → module → workspace).
    /// Workspaces define how file identifiers are generated (<see cref="NameMode"/>)
    /// and whether names are auto-generated or parsed from caller input (<see cref="ParseMode"/>).
    /// Virtual workspaces exist only in the DB and have no physical directory.
    /// </summary>
    internal class VaultWorkSpace : VaultComponent, IVaultWorkSpace {
        public IVaultObject Client { get; set; }
        public IVaultObject Module { get; set; }
        /// <summary>Name of the DB schema used by this workspace (reserved for future use).</summary>
        public string DatabaseName { get; set; }
        /// <summary>Defines whether stored files are identified by numeric IDs or compact-N GUIDs.</summary>
        public StorageNameMode NameMode { get; set; }
        /// <summary>Defines whether file identifiers are parsed from caller input or auto-generated by the indexer.</summary>
        public StorageNameParseMode ParseMode { get; set; }
        /// <summary>Base segment for this workspace's storage area (sharded directory for FS; key prefix for cloud).</summary>
        public string Base { get; set; }
        /// <summary>Optional override primary provider key. When set, takes precedence over the module's provider.</summary>
        public string StorageProviderKey { get; set; }
        /// <summary>Optional override staging provider key. When set, takes precedence over the module's staging provider.</summary>
        public string StagingProviderKey { get; set; }
        /// <summary>Upload routing mode override. Only effective when <see cref="StorageProviderKey"/> is set.</summary>
        public StorageProfileMode ProfileMode { get; set; } = StorageProfileMode.DirectSave;
        /// <summary>
        /// The dsscore.profile_info.id that was used to configure this workspace's provider settings.
        /// Set during <see cref="SetWorkspaceStorageProfile"/> hydration. 0 when the workspace was
        /// configured via <see cref="ConfigureWorkspaceProviders"/> (no DB-backed profile_info).
        /// Written to version_info.profile_info_id so files can always be resolved via their
        /// original profile rather than the module's current profile.
        /// </summary>
        public long ProfileInfoId { get; set; } = 0;

        /// <summary>Throws <see cref="ArgumentNullException"/> if required fields are missing or inconsistent.</summary>
        public void Assert() {
            if (string.IsNullOrWhiteSpace(DisplayName)) throw new ArgumentNullException("Name cannot be empty");
            if (!IsVirtual && (string.IsNullOrEmpty(StorageName) || string.IsNullOrEmpty(Base))) throw new ArgumentNullException("Base Cannot be empty");
            if (string.IsNullOrEmpty(Client?.Name) || string.IsNullOrWhiteSpace(Module?.Name)) throw new ArgumentNullException("Client & Module information cannot be empty");
        }
        public VaultWorkSpace(string clientName, string moduleName, string displayName, bool is_virtual = false):base(displayName) {
            IsVirtual = is_virtual;
            Client = new VaultObject(clientName);
            Module = new VaultObject(moduleName).UpdateCUID(clientName, moduleName);
            UpdateCUID(Client.Name, Module.Name, Name); //With all other names
        }
    }
}
