using Haley.Abstractions;
using Haley.Enums;
using System;
using System.Collections.Generic;
using System.Text;

namespace Haley.Models {
    /// <summary>
    /// Represents a workspace within the vault hierarchy (client → module → workspace).
    /// Workspaces define how file identifiers are generated (<see cref="ContentControl"/>)
    /// and whether names are auto-generated or parsed from caller input (<see cref="ContentParse"/>).
    /// Virtual workspaces exist only in the DB and have no physical directory.
    /// </summary>
    public class StorageWorkspace : VaultComponent, IVaultWorkSpace {
        /// <summary>Parent client reference required by <see cref="IVaultWorkSpace"/>.</summary>
        public IVaultBase Client { get; set; }      // IVaultWorkSpace requires IVaultBase
        /// <summary>Parent module reference required by <see cref="IVaultWorkSpace"/>.</summary>
        public IVaultBase Module { get; set; }      // IVaultWorkSpace requires IVaultBase
        /// <summary>Name of the DB schema used by this workspace (reserved for future use).</summary>
        public string DatabaseName { get; set; }
        /// <summary>Defines whether stored files are identified by numeric IDs or compact-N GUIDs.</summary>
        public VaultControlMode ContentControl { get; set; }
        /// <summary>Defines whether file identifiers are parsed from caller input or auto-generated by the indexer.</summary>
        public VaultParseMode ContentParse { get; set; }

        /// <summary>Throws <see cref="ArgumentNullException"/> if required fields are missing or inconsistent.</summary>
        public void Assert() {
            if (string.IsNullOrWhiteSpace(DisplayName)) throw new ArgumentNullException("Name cannot be empty");
            if (!IsVirtual &&  (string.IsNullOrEmpty(StorageName)  || string.IsNullOrEmpty(Path))) throw new ArgumentNullException("Path Cannot be empty");
            if ( string.IsNullOrEmpty(Client?.Name) || string.IsNullOrWhiteSpace(Module?.Name)) throw new ArgumentNullException("Client & Module information cannot be empty");
        }
        public StorageWorkspace(string clientName, string moduleName, string displayName, bool is_virtual = false):base(displayName) {
            IsVirtual = is_virtual;
            Client = new VaultInfo(clientName);
            Module = new VaultInfo(moduleName).UpdateCUID(clientName, moduleName);
            UpdateCUID(Client.Name, Module.Name, Name); //With all other names
        }
    }
}
